export const ADMINISTRATORS_LOAD_START = 'ADMINISTRATORS_LOAD_START';
export const ADMINISTRATORS_LOAD_DONE = 'ADMINISTRATORS_LOAD_DONE';
export const ADMINISTRATORS_LOAD_FAIL = 'ADMINISTRATORS_LOAD_FAIL';

export const ADMINISTRATORS_CHANGE_LIMIT_START = 'ADMINISTRATORS_CHANGE_LIMIT_START';
export const ADMINISTRATORS_CHANGE_LIMIT_FAIL = 'ADMINISTRATORS_CHANGE_LIMIT_FAIL';

export const ADMINISTRATORS_CHANGE_PAGE_START = 'ADMINISTRATORS_CHANGE_PAGE_START';
export const ADMINISTRATORS_CHANGE_PAGE_FAIL = 'ADMINISTRATORS_CHANGE_PAGE_FAIL';

export const ADMINISTRATORS_SEARCH_START = 'ADMINISTRATORS_SEARCH_START';
export const ADMINISTRATORS_SEARCH_FAIL = 'ADMINISTRATORS_SEARCH_FAIL';
