export const USERS_LOAD_START = 'USERS_LOAD_START';
export const USERS_LOAD_DONE = 'USERS_LOAD_DONE';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';

export const USERS_CHANGE_LIMIT_START = 'USERS_CHANGE_LIMIT_START';
export const USERS_CHANGE_LIMIT_FAIL = 'USERS_CHANGE_LIMIT_FAIL';

export const USERS_CHANGE_PAGE_START = 'USERS_CHANGE_PAGE_START';
export const USERS_CHANGE_PAGE_FAIL = 'USERS_CHANGE_PAGE_FAIL';

export const USERS_SEARCH_START = 'USERS_SEARCH_START';
export const USERS_SEARCH_FAIL = 'USERS_SEARCH_FAIL';
